baseURL = "https://dave.wittman.xyz/"
languageCode = "en-us"
title = "wittman.xyz"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
author = "Dave Wittman"
description = "Personal technology related ramblings of an AWS Janitor"
subtitle = "A tale of broken software"
mode = "toggle"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/DavidWittman"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/dave0ps"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/wittman/"

[services]
  [services.googleAnalytics]
    ID = "G-RRF5PMETE7"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2
